export const GET_EXPLORE_IMAGES_START = 'GET_EXPLORE_IMAGES_START';
export const GET_EXPLORE_IMAGES_SUCCESS = 'GET_EXPLORE_IMAGES_SUCCESS';
export const GET_EXPLORE_IMAGES_FAIL = 'GET_EXPLORE_IMAGES_FAIL';

export const GET_USER_IMAGES_START = 'GET_USER_IMAGES_START';
export const GET_USER_IMAGES_SUCCESS = 'GET_USER_IMAGES_SUCCESS';
export const GET_USER_IMAGES_FAIL = 'GET_USER_IMAGES_FAIL';

//authentication actions

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
