export const GET_EXPLORE_IMAGES_START = 'GET_EXPLORE_IMAGES_START';
export const GET_EXPLORE_IMAGES_SUCCESS = 'GET_EXPLORE_IMAGES_SUCCESS';
export const GET_EXPLORE_IMAGES_FAIL = 'GET_EXPLORE_IMAGES_FAIL';

export const GET_USER_IMAGES_START = 'GET_USER_IMAGES_START';
export const GET_USER_IMAGES_SUCCESS = 'GET_USER_IMAGES_SUCCESS';
export const GET_USER_IMAGES_FAIL = 'GET_USER_IMAGES_FAIL';
